#!/bin/bash

AUTHORIZED_KEYS_BASE="/etc/ssh/keys/"
APPLY_TO=""
NEW_KEY=""

if [ $# -ne 2 ]; then
  echo "Usage: addKey <applyTo> <newKey>"
  echo "  - <applyTo>  Methods to change. Possible values: 'ALL', method name"
  echo "  - <newKey>   New key to set"
  exit 1
fi;

APPLY_TO=$1
shift;

NEW_KEY=$1

ALL_METHODS=$(cat /etc/passwd | egrep '[0-9]:666:' | awk -F':' '{ print $1}')

# Spliting auth config to support several methods specification
IFS=',' read -r -a APPLY_METHODS <<< "${AUTH_CONFIG}"

for method in ${ALL_METHODS}; do
  # Trimming
  method=$(echo "${method}" | xargs)
  if [ $(echo ${method} | tr '[:lower:]') != "root" ] && [ [ ${method} == "ALL" ] || [ ${APPLY_METHODS[${method}]} ] ]; then
    local AUTH_KEYS_FILE="${AUTHORIZED_KEYS_BASE}/${method}_authorized_keys"
    grep "${NEW_KEY}" ${AUTH_KEYS_FILE} && echo "${NEW_KEY}" >> ${AUTH_KEYS_FILE}
  fi
done

