#!/bin/bash

SSHD_CONFIG="/etc/ssh/sshd_config"

APPLY_TO=""
AUTH_CONFIG=""

if [ $# -ne 2 ]; then
  echo "Usage: authConfig <applyTo> <authConfig>"
  echo "  - <applyTo>     Methods to change. Possible values: 'ALL', method name"
  echo "  - <authConfig>  Authentication mechanism. Possible values: 'NONE', 'PASSWORD', 'PUBLIC-KEY'"

  exit 1
fi;

APPLY_TO=$1
shift;

AUTH_CONFIG=$1

ALL_METHODS=$(cat /etc/passwd | egrep '[0-9]:666:' | awk -F':' '{ print $1}')

# Spliting auth config to support several methods specification
IFS=',' read -r -a APPLY_METHODS <<< "${AUTH_CONFIG}"

function updateSshdConfig(){
  METHOD=$1

  if [ "root" == $(echo "${METHOD}" | xargs) ] || [ "sftp" == $(echo "${METHOD}" | xargs) ]; then
    return
  fi

  # If method already exists, that block is replaced
  local MATCH_LINE=$(grep -n "Match User $METHOD" ${SSHD_CONFIG} | cut -f1 -d:)
  if [ -n "${MATCH_LINE}"]; then
    # If not it will be appended
    echo "Match User ${METHOD}" >> ${SSHD_CONFIG}
    MATCH_LINE=$(wc -l ${SSHD_CONFIG} | cut -f1 -d' ')
  fi

  # Setting new match block
  case "${AUTH_CONFIG}" in 
    NONE)
      sed -i "$((${MATCH_LINE} + 1))i PermitEmptyPasswords yes" ${SSHD_CONFIG}
      sed -i "$((${MATCH_LINE} + 2))i AuthenticationMethods 'password'" ${SSHD_CONFIG}
      sed -i "$((${MATCH_LINE} + 3))i " ${SSHD_CONFIG}
      ;;
    PASSWORD)
      sed -i "$((${MATCH_LINE} + 1))i AuthenticationMethods 'password'" ${SSHD_CONFIG}
      sed -i "$((${MATCH_LINE} + 2))i " ${SSHD_CONFIG}
      sed -i "$((${MATCH_LINE} + 3))i " ${SSHD_CONFIG}
      ;;
    PUBLIC-KEY)
      sed -i "$((${MATCH_LINE} + 1))i AuthenticationMethods 'publickey'" ${SSHD_CONFIG}
      sed -i "$((${MATCH_LINE} + 2))i " ${SSHD_CONFIG}
      sed -i "$((${MATCH_LINE} + 3))i " ${SSHD_CONFIG}
      ;;
  esac
}

LOCK_FILE="/tmp/authConfig.lock"
#Checking config lock
if [ -f ${LOCK_FILE} ]; then
    echo "Lock file (${LOCK_FILE}) preventing the config from being updated"
    exit 1;
else
    touch ${LOCK_FILE}
fi

for method in ${ALL_METHODS}; do
  # Trimming
  method=$(echo "${method}" | xargs)
  if [ $(echo ${method} | tr '[:lower:]') != "root" ] && [ $(echo ${method} | tr '[:lower:]') != "sftp" ]  && [ [ ${method} == "ALL" ] || [ ${APPLY_METHODS[${method}]} ] ]; then
    updateSshdConfig ${method}
  fi
done
#Releasing lock on config
rm ${LOCK_FILE}

#Apply new config
kill $(ps -e -o "pid,command" | grep "sshd -D" | grep -v "grep" | cut -f1 -d'/')

