#!/bin/bash

APPLY_TO=""
NEW_PASSWORD=""

if [ $# -ne 2 ]; then
  echo "Usage: changePassword <applyTo> <newPassword>"
  echo "  - <applyTo>     Methods to change. Possible values: 'ALL', method name"
  echo "  - <newPassword> New password to set"
  exit 1
fi;

APPLY_TO=$1
shift;

NEW_PASSWORD=$1

ALL_METHODS=$(cat /etc/passwd | egrep '[0-9]:666:' | awk -F':' '{ print $1}')

# Spliting auth config to support several methods specification
IFS=',' read -r -a APPLY_METHODS <<< "${AUTH_CONFIG}"

for method in ${ALL_METHODS}; do
  # Trimming
  method=$(echo "${method}" | xargs)
  if [ $(echo ${method} | tr '[:lower:]') != "root" ] && [ [ ${method} == "ALL" ] || [ ${APPLY_METHODS[${method}]} ] ]; then
    echo "${NEW_PASSWORD}" | passwd --stdin ${method}
  fi
done

