#!/bin/bash

AUTHORIZED_KEYS_BASE="/etc/ssh/keys/"
APPLY_TO=""

if [ $# -ne 1 ]; then
  echo "Usage: lsKey <method>"
  echo "  - <method>  Methods which keys to list. Possible values: 'ALL', method name"
  exit 1
fi;

APPLY_TO=$1
shift;

ALL_METHODS=$(cat /etc/passwd | egrep '[0-9]:666:' | awk -F':' '{ print $1}')

# Spliting auth config to support several methods specification
IFS=',' read -r -a APPLY_METHODS <<< "${APPLY_TO}"

# Check if ALL methods have been selected
if [ "$(echo ${APPLY_METHODS} | xargs)" == "ALL" ]; then
    APPLY_METHODS=${ALL_METHODS};
fi;

for method in ${ALL_METHODS}; do
  # Trimming
  typeset -l methodLower
  method=$(echo "${method}" | xargs)
  methodLower=$method
  if [ "${methodLower}" != "root" ] && [ ${ALL_METHODS[${method}]} ]; then
    echo "Keys registered for method $method"
    AUTH_KEYS_FILE="${AUTHORIZED_KEYS_BASE}/${method}_authorized_keys"
    if [ -f ${AUTH_KEYS_FILE} ]; then
        grep -n "" ${AUTH_KEYS_FILE}
    else
        echo "No keys defined"
    fi
  fi
done

